function [VI, ALLWIN, ALLSIG] = pop_addeventoptions(VI, ALLWIN, ALLSIG)
% [VI, ALLWIN, ALLSIG] = pop_addeventoptions(VI, ALLWIN, ALLSIG)

evtwin = findobj ('tag','addventoptions');
if ~isempty(evtwin)
    figure(evtwin);
    return;
end

figw = 250; figh = 215;       
h = figure ('visible','off','DockControls','on','units','pixel','position',[500,500,figw,figh],...
    'MenuBar','none','Name','Add Event (Options)','NumberTitle','off',...
    'Resize','off','color',vi_graphics('backgroundcolor'),'tag','addventoptions');

%- Type callbacks
cb_newtypecb = [
    'if isempty(VI.eventall); return; end;',...
    'val = get(findobj(gcbf,''tag'',''newtypecb''),''value'');',...
    'if val;',...
        'set (findobj(gcbf,''tag'',''newtypeedit''),''enable'',''on'');',...
        'try; set (findobj(gcbf,''tag'',''typepopup''),''enable'',''off'');end;',...        
    'else;',...
        'set (findobj(gcbf,''tag'',''newtypeedit''),''enable'',''off'');',...
        'try; set (findobj(gcbf,''tag'',''typepopup''),''enable'',''on'');end;',...
        'types = get(findobj(gcbf,''tag'',''typepopup''),''string'');',...
        'VI.guiparam.addevent.type = types{get(findobj(gcbf,''tag'',''typepopup''),''value'')};',...
    'end;',...
    ];
cb_existingtypespop = [
    'types = get(findobj(gcbf,''tag'',''typepopup''),''string'');',...
    'VI.guiparam.addevent.type = types{get(findobj(gcbf,''tag'',''typepopup''),''value'')};',...
    ];
cb_newtypeedit = [
    'VI.guiparam.addevent.type = get(findobj(gcbf,''tag'',''newtypeedit''),''string'');',...
    ];

type_p      = uipanel (h,'title','Type','Units','normalized','position',    [0.025,0.6,0.95,0.38]);
channel_p   = uipanel (h,'title','Channel','Units','normalized','position', [0.025,0.2,0.95,0.38]);
time_p      = uipanel (h,'title','Time','Units','normalized','position',    [0.025,0.01,0.95,0.18]);
uicontrol (type_p,'style','text','string','Existing Types : ','Units','normalized','position',[0.05,0.6,0.4,0.3],...
    'fontsize',vi_graphics('fontsize_base'),'horizontalalignment','left','callback','');
newtypeon = 1;
if ~isempty(VI.eventall)
    eventtypes = unique({VI.eventall.type});
    eventtypepos = find(strcmp(eventtypes,VI.guiparam.addevent.type)~=0);
    if isempty(eventtypepos); eventtypepos=1; newtypeon=1; else newtypeon=0; end;
    uicontrol (type_p,'style','popup','string',eventtypes,'value',eventtypepos,'Units','normalized','position',[0.55,0.6,0.4,0.3],...
        'fontsize',vi_graphics('fontsize_base'),'tag','typepopup','callback',cb_existingtypespop,'enable',fastif(newtypeon,'off','on'));
    uicontrol (type_p,'style','checkbox','Units','normalized','position',[0.4,0.1,0.1,0.3],...
        'tag','newtypecb','value',newtypeon,'callback',cb_newtypecb);
end
uicontrol (type_p,'style','text','string','New Type : ','Units','normalized','position',[0.05,0.1,0.3,0.3],...
    'fontsize',vi_graphics('fontsize_base'),'horizontalalignment','left');
if newtypeon; newtypestr = VI.guiparam.addevent.type; else newtypestr=''; end;
uicontrol (type_p,'style','edit','string',newtypestr,'Units','normalized','position',[0.55,0.1,0.4,0.3],'enable',fastif(newtypeon,'on','off'),...
    'tag','newtypeedit','callback',cb_newtypeedit);


%- Channel information callbacks
cb_globalevent = [
    'val = get(findobj(gcbf,''tag'',''globalevcb''),''value'');',...
    'if val;',...
        'set (findobj(gcbf,''tag'',''channelevcb''),''value'',0);',...
        'VI.guiparam.addevent.channel=''global'';',...
    'else;',...
        'set (findobj(gcbf,''tag'',''channelevcb''),''value'',1);',...
    'end;',...
    ];
cb_channelevent = [
    'val = get(findobj(gcbf,''tag'',''channelevcb''),''value'');',...
    'if val;',...
        'set (findobj(gcbf,''tag'',''globalevcb''),''value'',0);',...
        'VI.guiparam.addevent.channel=''channel'';',...
    'else;',...
        'set (findobj(gcbf,''tag'',''globalevcb''),''value'',1);',...
    'end;',...
    ];

channelcbval = fastif (strcmp(VI.guiparam.addevent.channel,'channel'), 1, 0);
uicontrol (channel_p,'style','text','string','Global Event','Units','normalized','position',[0.05,0.6,0.6,0.3],...
    'fontsize',vi_graphics('fontsize_base'),'horizontalalignment','left','callback','');
uicontrol (channel_p,'style','checkbox','Units','normalized','position',[0.85,0.7,0.1,0.2],...
    'value',~channelcbval,'tag','globalevcb','callback',cb_globalevent);
uicontrol (channel_p,'style','text','string','Channel Specific Event','Units','normalized','position',[0.05,0.1,0.8,0.3],...
    'fontsize',vi_graphics('fontsize_base'),'horizontalalignment','left','callback','');
uicontrol (channel_p,'style','checkbox','Units','normalized','position',[0.85,0.2,0.1,0.2],...
    'value',channelcbval,'tag','channelevcb','callback',cb_channelevent);

%- Time 
cb_discretetimeevent = [
    'val = get(findobj(gcbf,''tag'',''discretetimeeventcb''),''value'');',...
    'if val;',...
        'VI.guiparam.addevent.discretetime=1;',...
    'else;',...
        'VI.guiparam.addevent.discretetime=0;',...
    'end;',...
    ];

uicontrol (time_p,'style','text','string','Discrete Event','Units','normalized','position',[0.05,0.1,0.6,0.8],...
    'fontsize',vi_graphics('fontsize_base'),'horizontalalignment','left');
uicontrol (time_p,'style','checkbox','Units','normalized','position',[0.85,0.1,0.1,0.8],...
    'fontsize',vi_graphics('fontsize_base'),'horizontalalignment','left','tag','discretetimeeventcb','callback',cb_discretetimeevent);

set (h,'visible','on');

        
end

