function [VI, ALLWIN, ALLSIG] = pop_seeevents(VI, ALLWIN, ALLSIG)
% [VI, ALLWIN, ALLSIG] = pop_seeevents(VI, ALLWIN, ALLSIG)
% Open the event panel, cen be used to navigate/order/sort/delete events
%
% See also updateeventsel, orderevents, navigateevent

evtwin = findobj ('tag','eventwindow');
if ~isempty(evtwin)
    figure(evtwin);
    return;
end

resize_cb = [
    'figpos         = get(gcbf,''Position'');',...
    'topp           = findobj(gcbf,''tag'',''topp'');',...
    'orderp         = findobj(gcbf,''tag'',''orderp'');',...
    'selectp        = findobj(gcbf,''tag'',''selectp'');',...
    'navigp         = findobj(gcbf,''tag'',''navigp'');',...
    'importpb       = findobj(gcbf,''tag'',''importpb'');',...
    'exportpb       = findobj(gcbf,''tag'',''exportpb'');',...
    'convertpb      = findobj(gcbf,''tag'',''convertpb'');',...
    'set (topp,''Units'',''pixels'',''Position'',[0.025*figpos(3),0.6*450,0.95*figpos(3),figpos(4)-0.62*450]);',...
    'set (orderp,''Units'',''pixels'',''Position'',[0.025*figpos(3),0.51*450,0.95*figpos(3),0.09*450]);',...
    'set (selectp,''Units'',''pixels'',''Position'',[0.025*figpos(3),0.20*450,0.95*figpos(3),0.30*450]);',...
    'set (navigp,''Units'',''pixels'',''Position'',[0.025*figpos(3),0.085*450,0.95*figpos(3),0.11*450]);',...
    'set (importpb,''Units'',''pixels'',''Position'',[0.1*figpos(3),0.01*450,0.2*figpos(3),0.045*450]);',...
    'set (exportpb,''Units'',''pixels'',''Position'',[0.4*figpos(3),0.01*450,0.2*figpos(3),0.045*450]);',...    
    'set (convertpb,''Units'',''pixels'',''Position'',[0.7*figpos(3),0.01*450,0.2*figpos(3),0.045*450]);',...    
];

figw = 420; figh = 450;       
h = figure ('visible','off','DockControls','on','units','pixel','position',[200,200,figw,figh],...
            'MenuBar','none','Name','Events','NumberTitle','off','ResizeFcn',resize_cb,...
            'Resize','on','color',vi_graphics('backgroundcolor'),'tag','eventwindow');

top_p = uipanel ('title','Events','Units','normalized','position',[0.025,0.61,0.95,0.38],'tag','topp');
%--- Event table panel -----------------------
t = uitable('Parent', top_p, 'Units','normalized','position', [0.01,0.01,0.98,0.98],'tag','eventtable');
%- Populate the table
eventdata   = VI.eventall;
durationstr = arrayfun(@(x)sprintf('%.2f',x.duration),eventdata,'Uniformoutput',false);
tposstr     = arrayfun(@(x)sprintf('%.2f',x.tpos),eventdata,'Uniformoutput',false);
freqstr     = arrayfun(@(x)sprintf('%d',x.centerfreq),eventdata,'Uniformoutput',false);
nevent      = length(VI.eventall);
if ~isempty(eventdata)
    eventposcell            = num2cell(1:nevent);% mat2cell((1:nevent)',ones(nevent,1),1);
    [eventdata.eventpos]    = eventposcell{:};
    [eventdata.duration] 	= durationstr{:};
    [eventdata.tpos]        = tposstr{:};
    [eventdata.centerfreq]  = freqstr{:};
    
    nfields     = length(fieldnames(eventdata));
    eventdata   = orderfields(eventdata,[nfields,2:nfields-1,1]);
    eventdata   = squeeze(struct2cell(eventdata))';
    %- Remove channelind, sigid, rawparentid fields
    eventdata(:,[5,7,9,11])=[];
    
    set (t, 'data',eventdata);
    set (t, 'ColumnName', {'','Type','Time (s)','Duration (s)','Channel','Signal','Frequency (Hz)'});
    set (t, 'ColumnWidth',{15,'auto','auto','auto','auto','auto','auto','auto'});
    set (t, 'RowName', []);
    set (t, 'ColumnEditable', [false true false false false false false]);
    set (t, 'CellEditCallback', @eventui_celledit);
    set (t, 'CellSelectionCallback', @eventui_cellselect);
    
    etypes      = unique(eventdata(:,2));   etypes      = ['All';etypes];
    esigdesc    = unique(eventdata(:,6));   esigdesc    = ['All';esigdesc];
    echannames  = unique(eventdata(:,5));   echannames  = ['All';echannames];
else
    etypes      = {''};
    esigdesc    = {''};
    echannames  = {''};
end
%- Init the event selection
VI.eventsel=VI.eventall;

%--- Ordering panel ----------------------
eventorderfields = {'','type','time','duration','channel','signal','frequency'};
order_p = uipanel ('title','Order','Units','normalized','position',[0.025,0.51,0.95,0.09],'tag','orderp');
uicontrol (order_p,'style','text','string','Order by : ','Units','normalized','position',[0.02,0.1,0.18,0.8],...
    'fontsize',vi_graphics('fontsize_base'));
uicontrol (order_p,'style','popup','string',eventorderfields,'Units','normalized','tag','ordersel1',...
    'position',[0.22,0.15,0.2,0.85],'fontsize',vi_graphics('fontsize_base'),'callback','VI = orderevents(VI);',...
    'value',find(strcmp(eventorderfields,VI.guiparam.seeevents.order1)==1));
uicontrol (order_p,'style','popup','string',eventorderfields,'Units','normalized','tag','ordersel2',...
    'position',[0.45,0.15,0.2,0.85],'fontsize',vi_graphics('fontsize_base'),'callback','VI = orderevents(VI);',...
    'value',find(strcmp(eventorderfields,VI.guiparam.seeevents.order2)==1),'enable',fastif(isempty(VI.guiparam.seeevents.order2),'off','on'));
uicontrol (order_p,'style','popup','string',eventorderfields,'Units','normalized','tag','ordersel3',...
    'position',[0.68,0.15,0.2,0.85],'fontsize',vi_graphics('fontsize_base'),'callback','VI = orderevents(VI);',...
    'value',find(strcmp(eventorderfields,VI.guiparam.seeevents.order3)==1),'enable',fastif(isempty(VI.guiparam.seeevents.order2),'off','on'));



%--- Selection panel --------------------
select_p = uipanel ('title','Selection','Units','normalized','position',[0.025,0.20,0.95,0.30],'tag','selectp');
uicontrol (select_p,'style','text','string','Number of events :','Units','normalized',...
    'position',[0.025,0.8,0.3,0.15],'fontsize',vi_graphics('fontsize_base'),'HorizontalAlignment','left');
uicontrol (select_p,'style','text','string',num2str(nevent),'Units','normalized','tag','noetext','ForegroundColor',[0,0,1],...
    'position',[0.35,0.8,0.15,0.15],'fontsize',vi_graphics('fontsize_base')+1,'HorizontalAlignment','left');
uicontrol (select_p,'style','text','string','Select All','Units','normalized',...
    'position',[0.7,0.8,0.18,0.15],'fontsize',vi_graphics('fontsize_base'),'HorizontalAlignment','center');
uicontrol (select_p,'style','checkbox','Units','normalized','tag','selallcb','callback','VI = updateeventsel(VI);',...
    'position',[0.9,0.8,0.08,0.15],'fontsize',vi_graphics('fontsize_base'),'HorizontalAlignment','left');
uicontrol (select_p,'style','text','string','Exclude','Units','normalized',...
    'position',[0.51,0.62,0.15,0.15],'fontsize',7);
%-- Type selection
uicontrol (select_p,'style','text','string','Type :','Units','normalized',...
    'position',[0.06,0.5,0.15,0.15],'fontsize',vi_graphics('fontsize_base'),'HorizontalAlignment','left');
uicontrol (select_p,'style','popup','string',etypes,'Units','normalized','tag','typepop',...
    'position',[0.2,0.5,0.3,0.15],'fontsize',vi_graphics('fontsize_base'),'callback','VI = updateeventsel(VI);');
uicontrol (select_p,'style','checkbox','Units','normalized','tag','extypecb','callback','VI = updateeventsel(VI);',...
    'position',[0.57,0.5,0.15,0.15],'fontsize',vi_graphics('fontsize_base'),'HorizontalAlignment','left');
%-- Signal selection
uicontrol (select_p,'style','text','string','Signal :','Units','normalized',...
    'position',[0.06,0.3,0.15,0.15],'fontsize',vi_graphics('fontsize_base'),'HorizontalAlignment','left');
uicontrol (select_p,'style','popup','string',esigdesc,'Units','normalized','tag','sigpop',...
    'position',[0.2,0.3,0.3,0.15],'fontsize',vi_graphics('fontsize_base'),'callback','VI = updateeventsel(VI);');
uicontrol (select_p,'style','checkbox','Units','normalized','tag','exsigcb','callback','VI = updateeventsel(VI);',...
    'position',[0.57,0.3,0.15,0.15],'fontsize',vi_graphics('fontsize_base'),'HorizontalAlignment','left');
%-- Channel selection
uicontrol (select_p,'style','text','string','Channel :','Units','normalized',...
    'position',[0.06,0.1,0.15,0.15],'fontsize',vi_graphics('fontsize_base'),'HorizontalAlignment','left');
uicontrol (select_p,'style','popup','string',echannames,'Units','normalized','tag','chanpop',...
    'position',[0.2,0.1,0.3,0.15],'fontsize',vi_graphics('fontsize_base'),'callback','VI = updateeventsel(VI);');
uicontrol (select_p,'style','checkbox','Units','normalized','tag','exchancb','callback','VI = updateeventsel(VI);',...
    'position',[0.57,0.1,0.15,0.15],'fontsize',vi_graphics('fontsize_base'),'HorizontalAlignment','left');
%-- Delete selection
cb_deleteeventsel = [
    '[~,eventsel] = updateeventsel (VI, 1);',...
    'if sum(eventsel)==0; return; end;',...
    'if strcmp(questdlg([''Delete '',num2str(sum(eventsel)),'' events ?'']),''Yes'');',...
    'VI.eventall(eventsel) = [];',...
    'VI.eventpos = median([0,length(VI.eventsel)-sum(eventsel),VI.eventpos]);',...
    'if isempty(VI.eventpos); VI.eventpos=0; end;',...
    'VI = updateeventsel (VI,1,1);',...
    'for winnb=VI.figh; ALLWIN = redrawwin(VI, ALLWIN, ALLSIG, winnb); end;',...
    'end;',...
    ];

cb_changecolor = [
    'c = uisetcolor();'...
    'if c==0; return; end;',...
    '[~,eventsel] = updateeventsel (VI, 1);',...
    'VI.eventsel  = arrayfun(@(s)setfield(s,''color'',c),VI.eventsel);',...
    'VI.eventall(eventsel) = VI.eventsel;',...
    'for winnb=VI.figh; ALLWIN = redrawwin(VI, ALLWIN, ALLSIG, winnb); end;',...
    'set(findobj(''tag'',''changecolorpb''),''ForegroundColor'',c);',...
    ];
uicontrol (select_p,'style','pushbutton','string','Delete','Units','normalized','Callback',cb_deleteeventsel,...
    'position',[0.8,0.03,0.15,0.2],'fontsize',vi_graphics('fontsize_base'),'HorizontalAlignment','left');
uicontrol (select_p,'style','pushbutton','string','Color','Units','normalized','Callback',cb_changecolor,'tag','changecolorpb',...
    'position',[0.67,0.03,0.09,0.2],'fontsize',vi_graphics('fontsize_base'),'HorizontalAlignment','left');


%--- Navigation panel --------------------
cb_deleteevent = [
    'if isempty(VI.eventsel) || isempty(VI.eventpos) || VI.eventpos==0; return; end;',...
    '[~,eventselind] = getevents (VI,''eventid'',VI.eventsel(VI.eventpos).id);',...
    'VI.eventall(eventselind) = [];',...
    'VI.eventsel(VI.eventpos) = [];',...
    'VI.eventpos = max(0,VI.eventpos-1);',...
    'VI     = updateeventsel (VI);',...
    'for winnb=VI.figh; ALLWIN = redrawwin(VI, ALLWIN, ALLSIG, winnb); end;',...
    ];
    
navig_p = uipanel ('title','Navigation','Units','normalized','position',[0.025,0.085,0.95,0.11],'tag','navigp');
uicontrol (navig_p,'style','pushbutton','string','<','Units','normalized','position',[0.15,0.15,0.12,0.7],...
    'tag','previouseventpb','callback','[VI,ALLWIN,ALLSIG]=navigateevent(VI,ALLWIN,ALLSIG);');
uicontrol (navig_p,'style','pushbutton','string','>','Units','normalized','position',[0.3,0.15,0.12,0.7],...
    'tag','nexteventpb','callback','[VI,ALLWIN,ALLSIG]=navigateevent(VI,ALLWIN,ALLSIG);');
uicontrol (navig_p,'style','edit','string',num2str(VI.eventpos),'Units','normalized','position',[0.5,0.2,0.2,0.6],...
    'fontsize',vi_graphics('fontsize_base')+1,'tag','navigedit','callback','[VI,ALLWIN,ALLSIG]=navigateevent(VI,ALLWIN,ALLSIG);');
uicontrol (navig_p,'style','pushbutton','string','Delete','Units','normalized','position',[0.8,0.15,0.15,0.7],...
    'fontsize',vi_graphics('fontsize_base'),'callback',cb_deleteevent);

%-- Export and import
% uicontrol (h,'style','pushbutton','string','Import','Units','normalized','position',[0.2,0.01,0.2,0.045],...
%      'fontsize',vi_graphics('fontsize_base'),'callback','VI=importeventsfromfile(VI);','tag','importpb');
% uicontrol (h,'style','pushbutton','string','Export','Units','normalized','position',[0.6,0.01,0.2,0.045],...
%      'fontsize',vi_graphics('fontsize_base'),'callback','exporteventstofile(VI)','tag','exportpb');
uicontrol (h,'style','pushbutton','string','Import','Units','normalized','position',[0.1,0.01,0.2,0.045],...
     'fontsize',vi_graphics('fontsize_base'),'callback','VI=importeventsfromfile(VI);','tag','importpb');
uicontrol (h,'style','pushbutton','string','Export','Units','normalized','position',[0.4,0.01,0.2,0.045],...
     'fontsize',vi_graphics('fontsize_base'),'callback','exporteventstofile(VI)','tag','exportpb');
uicontrol (h,'style','pushbutton','string','Convert to Sig','Units','normalized','position',[0.7,0.01,0.2,0.045],...
     'fontsize',vi_graphics('fontsize_base'),'callback','[VI,ALLWIN,ALLSIG]=pop_event2sigevent(VI, ALLWIN, ALLSIG, 1);','tag','convertpb');

set (h,'visible','on');

[VI] = orderevents (VI,h);

end



